//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testDabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class mise
    {
        public int id { get; set; }
        public double montant { get; set; }
        public double cout { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> id_produit { get; set; }
        public Nullable<int> id_statut_mise { get; set; }
        public Nullable<int> id_utilisateur { get; set; }
    
        public virtual produit produit { get; set; }
        public virtual statut_mise statut_mise { get; set; }
        public virtual utilisateur utilisateur { get; set; }
    }
}
