//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testDabaseFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeamTimDbTestEntities : DbContext
    {
        public TeamTimDbTestEntities()
            : base("name=TeamTimDbTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actualite> actualite { get; set; }
        public virtual DbSet<categorie_produit> categorie_produit { get; set; }
        public virtual DbSet<historique_credit> historique_credit { get; set; }
        public virtual DbSet<mise> mise { get; set; }
        public virtual DbSet<produit> produit { get; set; }
        public virtual DbSet<question> question { get; set; }
        public virtual DbSet<reponse> reponse { get; set; }
        public virtual DbSet<statut_mise> statut_mise { get; set; }
        public virtual DbSet<statut_produit> statut_produit { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<type_utilisateur> type_utilisateur { get; set; }
        public virtual DbSet<utilisateur> utilisateur { get; set; }
    }
}
