//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testDabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class produit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produit()
        {
            this.mise = new HashSet<mise>();
        }
    
        public int id { get; set; }
        public string libelle { get; set; }
        public string reference { get; set; }
        public string description { get; set; }
        public double prix_base { get; set; }
        public System.DateTime date_debut_vente { get; set; }
        public Nullable<System.DateTime> date_fin_vente { get; set; }
        public string image { get; set; }
        public double marge { get; set; }
        public string commentaire { get; set; }
        public bool est_dans_panier { get; set; }
        public Nullable<int> id_categorie_produit { get; set; }
        public Nullable<int> id_statut_produit { get; set; }
        public Nullable<int> id_utilisateur_gagnant { get; set; }
        public Nullable<int> id_utilisateur_vente { get; set; }
    
        public virtual categorie_produit categorie_produit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mise> mise { get; set; }
        public virtual statut_produit statut_produit { get; set; }
        public virtual utilisateur utilisateur { get; set; }
        public virtual utilisateur utilisateur1 { get; set; }
    }
}
