//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db2019EventsStudentEntities : DbContext
    {
        public Db2019EventsStudentEntities()
            : base("name=Db2019EventsStudentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Association> Association { get; set; }
        public virtual DbSet<Drink> Drink { get; set; }
        public virtual DbSet<DrinkType> DrinkType { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<EventType> EventType { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<Participation> Participation { get; set; }
        public virtual DbSet<Path> Path { get; set; }
        public virtual DbSet<Route> Route { get; set; }
        public virtual DbSet<School> School { get; set; }
        public virtual DbSet<Stop> Stop { get; set; }
    }
}
